apiVersion: v1
kind: Service
metadata:
  name: presentation-gitlab-k8s-live
  namespace: presentation-gitlab-k8s
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: live
  sessionAffinity: None
  type: ClusterIP
